insert into teams (id,  name, season) values (1, 'Dallas Renegades', 2019);
insert into teams (id,  name, season) values (2, 'Dallas Renegades', 2018);
insert into teams (id,  name, season) values (3, 'Dallas Renegades', 2017);
insert into teams (id,  name, season) values (4, 'Houston Roughnecks', 2019);
insert into teams (id,  name, season) values (5, 'Houston Roughnecks', 2018);
insert into teams (id,  name, season) values (6, 'Houston Roughnecks', 2017);
insert into teams (id,  name, season) values (7, 'Los Angeles Wildcats', 2019);
insert into teams (id,  name, season) values (8, 'Los Angeles Wildcats', 2018);
insert into teams (id,  name, season) values (9, 'Los Angeles Wildcats', 2017);
insert into teams (id,  name, season) values (10, 'New York Guardians', 2019);
insert into teams (id,  name, season) values (11, 'New York Guardians', 2018);
insert into teams (id,  name, season) values (12, 'New York Guardians', 2017);
insert into teams (id,  name, season) values (13, 'St. Louis BattleHawks', 2019);
insert into teams (id,  name, season) values (14, 'St. Louis BattleHawks', 2018);
insert into teams (id,  name, season) values (15, 'St. Louis BattleHawks', 2017);
insert into teams (id,  name, season) values (16, 'Seattle Dragons', 2019);
insert into teams (id,  name, season) values (17, 'Seattle Dragons', 2018);
insert into teams (id,  name, season) values (18, 'Seattle Dragons', 2017);
insert into teams (id,  name, season) values (19, 'Tampa Bay Vipers', 2019);
insert into teams (id,  name, season) values (20, 'Tampa Bay Vipers', 2018);
insert into teams (id,  name, season) values (21, 'Tampa Bay Vipers', 2017);
insert into teams (id,  name, season) values (22, 'D.C. Defenders', 2019);
insert into teams (id,  name, season) values (23, 'D.C. Defenders', 2018);
insert into teams (id,  name, season) values (24, 'D.C. Defenders', 2017);