update teams set name = 'Charlotte Hornets' where name = 'Charlotte Bobcats';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/bos.png' where name = 'Boston Celtics';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/bkn.png' where name = 'Brooklyn Nets';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/ny.png' where name = 'New York Knicks';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/phi.png' where name = 'Philadelphia 76ers';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/tor.png' where name = 'Toronto Raptors';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/chi.png' where name = 'Chicago Bulls';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/cle.png' where name = 'Cleveland Cavaliers';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/det.png' where name = 'Detroit Pistons';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/ind.png' where name = 'Indiana Pacers';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/mil.png' where name = 'Milwaukee Bucks';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/atl.png' where name = 'Atlanta Hawks';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/cha.png' where name = 'Charlotte Hornets';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/mia.png' where name = 'Miami Heat';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/orl.png' where name = 'Orlando Magic';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/wsh.png' where name = 'Washington Wizards';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/gs.png' where name = 'Golden State Warriors';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/lac.png' where name = 'Los Angeles Clippers';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/lal.png' where name = 'Los Angeles Lakers';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/phx.png' where name = 'Phoenix Suns';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/sac.png' where name = 'Sacramento Kings';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/dal.png' where name = 'Dallas Mavericks';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/hou.png' where name = 'Houston Rockets';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/mem.png' where name = 'Memphis Grizzlies';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/no.png' where name = 'New Orleans Pelicans';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/sa.png' where name = 'San Antonio Spurs';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/den.png' where name = 'Denver Nuggets';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/min.png' where name = 'Minnesota Timberwolves';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/okc.png' where name = 'Oklahoma City Thunder';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/por.png' where name = 'Portland Trail Blazers';
update teams set url = 'a.espncdn.com/i/teamlogos/nba/500/utah.png' where name = 'Utah Jazz';

